import { VStack, Container } from '@chakra-ui/layout'
import Head from 'next/head'
import Image from 'next/image'

import { useColorMode } from '@chakra-ui/color-mode'

import Header from '../components/Header'
import Footer from '../components/Footer'
import BioCard from '../components/BioCard'
import SkillsCard from '../components/SkillsCard'
import BlogBtnCard from '../components/BlogBtnCard'
import ProjectsBtnCard from '../components/ProjectsBtnCard'
import ContactCard from '../components/ContactCard'
import MyMessageCard from '../components/MyMessageCard'
// custom dummy components
import CustomComponentOne from '../components/CustomComponentOne'
import CustomComponentTwo from '../components/CustomComponentTwo'
import CustomComponentThree from '../components/CustomComponentThree'
import CustomComponentFour from '../components/CustomComponentFour'
import CustomComponentFive from '../components/CustomComponentFive'

import Masonry from 'react-masonry-css'

// responsive breakpoints for masonry grid. Cant be easily adjusted here
const breakpointColumnsObj = {
  default: 3,
  800: 2,
  600: 1
};

export default function Home() {
  const { colorMode } = useColorMode()

  return (
    <div>
      <Head>
        <title>Nextjs Bloggin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack minHeight="100vh" bgGradient={colorMode === 'light' ? "linear(to-r, #1F1C2C, #928DAB)" : "linear(to-r, #0F2027, #203A43, #24243e)"}>
        <Container maxW="960">
          <Header/>
            <Masonry
            breakpointCols={breakpointColumnsObj}
            className="my-masonry-grid"
            columnClassName="my-masonry-grid_column"
            >
            <BioCard/>
            <ContactCard/>
            <MyMessageCard/>
            <SkillsCard/>
            <BlogBtnCard/>
            <ProjectsBtnCard/>
            <CustomComponentOne/>
            <CustomComponentTwo/>
            <CustomComponentThree/>
            <CustomComponentFour/>
            <CustomComponentFive/>
            </Masonry>
          <Footer/>
        </Container>
      </VStack>

    </div>
  )
}
